### ISSUE TITLE
Brainstorm NDG voting activities

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#31]
## Goal:

Have a draft list of activities we could do as a community to support the NDG referendum efforts.
## Success:

We have at least 3 different agreed activities we are carrying out over the summer.
## Related Issues & Links:

[objective] #4 
## Roles:

Owner: @MichaelKohler
Involved: @J0WI, everyone else
## Required:
- [ ] Brainstorm on possible activities (all, [medium], Due: 31.05.2016) 
- [ ] Come up with a plan to do those activities (all, [medium], Due: 05.06.2016)

**Comment by MichaelKohler** [comment]
One idea in the meeting yesterday was to draft an open letter "to the Swiss voters". Do you think that would have impact? Should we do this alone or get the other allies on board as well? We probably can't fund 3 million (or even more) letters, but we could publish this online. What do you think?

Other ideas I had:
- [ ] Print a few flyers with a kick-ass design and distribute them
- [ ] Start a comic about this law and spread it through the internet
- [ ] Keep doing privacy talks under the Mozilla umbrella

Please share your ideas as well, thanks!

**Comment by J0WI** [comment]
The letter is a good idea and it could have an impact if we reach the press. If we have officially support by Mozilla, it's very likely, that some tech magazines will take attention. The hard part is, that this will be surprising or important enough for the mainstream news.

Here are some requirements:
- campaign site (maybe a mix of customized [get smart on](https://www.mozilla.org/de/teach/smarton/surveillance/) and [petitions](https://petitions.mozilla.org/))
- translation, at least D/F
- media to share (comic is a great idea)

If we can't get a campaign site, the letter should be published somewhere on mozilla.org.
Furthermore Mozilla may join the 'supported by' list of existing campaign sites.

When we print flyers, we really need to distribute them on railway stations or so. That's quite hard since we are not that many people. I think this is something that common parties will do.
Posters are great, but far more expensive.

Btw: Does Mozilla already make a difference between German/French and Switzerland? This would be important for translation and audience stuff.

**Comment by MichaelKohler** [comment]
Great input, thanks for joining into this that quickly!

> campaign site (maybe a mix of customized get smart on and petitions)

Great idea, we could create a sub page on mozilla.ch for example? I think we're pretty free on what we do with that as long as it's within our mission :)

> Btw: Does Mozilla already make a difference between German/French and Switzerland? This would be important for translation and audience stuff.

Not in terms of l10n. I'm not sure if I understand the audience part of it though.

**Comment by J0WI** [comment]
> Great idea, we could create a sub page on mozilla.ch for example? I think we're pretty free on what we do with that as long as it's within our mission :)

I think it has a different effect, if the statement is just from mozilla.ch or in the name of the Mozilla Foundation.

**Comment by MichaelKohler** [comment]
> I think it has a different effect, if the statement is just from mozilla.ch or in the name of the Mozilla Foundation.

We could use it as a hub, and also post it to mozilla.org. I think that would work.

**Comment by J0WI** [comment]
Okay, but then we need a solid solution for #16 first.

**Comment by MichaelKohler** [comment]
Do we have any other ideas here?

**Comment by freaktechnik** [comment]
Feel free to re-open if you think we can still achieve something meaningful here in the remaining time.
