### ISSUE TITLE
Get a Rust intro by Rust Switzerland Community in June

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/participation#33]
## Goal:

Have an introduction to the Rust community in Switzerland and get educated about Rust.
## Success:

We have at least 2 contact persons in the Rust community to plan for future events.
## Roles:

Owner: @freaktechnik 
Involved: @MichaelKohler
## Required:
- [x] Get in touch with the Rust community (@MichaelKohler, medium, Due: 15.4.2016)
- [x] Start to organize an Intro talk at our meetups (@MichaelKohler, medium, Due: 30.05.2016)
- [ ] Start organizing a Servo / Graphene hackathon with those people (???, large, Due: 30.06.2016)

**Comment by freaktechnik** [comment]
Someone with telegram should try http://www.meetup.com/Rust-Zurich/messages/boards/thread/49749350/

**Comment by MichaelKohler** [comment]
Just got in touch with this group, general interest is there as it seems :)

**Comment by dbrgn** [comment]
Yes, I'd say we're generally interested :) We're members of the @coredump-ch hackerspace in Rapperswil. Some of us (mostly @rnestler, @dns2utf8 and me) are hacking with Rust since about a year. Among others:
- https://github.com/coredump-ch/spaceapi-rs
- https://github.com/coredump-ch/spaceapi-server-rs
- https://github.com/coredump-ch/status
- https://github.com/coredump-ch/coredumpbot

@rnestler and me are probably going to give an "Intro to Rust" talk at the Cosin this year (website is down unfortunately). We could also do that twice and host another one in our Hackerspace.

A hackathon on Servo or any Rust projects in general is also something that we could do sometime. We could probably host around 16 to max 20 people.

**Comment by MichaelKohler** [comment]
@dbrgn would any of the following dates (at around 7pm) work for you to have an intro talk in Zurich?

22.06.
23.06.
29.06.
30.06.

Would be great to have somebody of you there and give a talk :)

Then we could also start to plan for a Servo hackathon around the end of summer.

**Comment by dns2utf8** [comment]
I prefere the wednesdays.

I would like to help with the hackaton, but my timewindow at the end of summer is 5. - 16. september.

**Comment by dbrgn** [comment]
23.06. collides with the Blues'n'Jazz festival.

For me, the 30. would be best, but 23. or 29. would work too.

@rnestler, what about you?

**Comment by rnestler** [comment]
23.06 is bad for me as well. Good would be:
- 22.06
- 30.06

29.06 would also be OK, but I would prefer the other two dates.

So I guess 30.06 it is?

**Comment by MichaelKohler** [comment]
Perfect, thanks a lot everyone!

@colinfrei could you please reserve the Arena for the 30.06. at 19:00? Thanks!

I will create the meetup page and promote it after the location is set.

**Comment by dbrgn** [comment]
If you want, you can take the description from https://etherpad.coredump.ch/p/rust-talk-cosin16.

**Comment by colinfrei** [comment]
Room booked.

**Comment by MichaelKohler** [comment]
Thanks Colin!

http://www.meetup.com/Mozilla-Meetup-Switzerland/events/231268531/
https://reps.mozilla.org/e/introduction-to-rust/
http://techup.ch/2315/introduction-to-rust

https://twitter.com/MozillaCH/status/733629746551107584
Announced to the mailinglist as well. 
Sent mail to LUGS Termine to add it to their calendar

Everyone, please use your channels to announce this as well :)

Let's talk about the hackathon at this meetup as well.
